export const VIEW_MODES = {
  table: "table",
  kanban: "kanban",
};

export const RECRUITLY__JOB_PIPELINE_TABLE_CANDIDATE_NAME_COLUMN_WIDTH_LS = "RECRUITLY__JOB_PIPELINE_TABLE_CANDIDATE_NAME_COLUMN_WIDTH";
export const RECRUITLY__JOB_PIPELINE_TABLE_JOB_NAME_COLUMN_WIDTH_LS = "RECRUITLY__JOB_PIPELINE_TABLE_JOB_NAME_COLUMN_WIDTH";
export const RECRUITLY__JOB_PIPELINE_BOARD_COLUMN_WIDTH_LS = "RECRUITLY__JOB_PIPELINE_BOARD_COLUMN_WIDTH";

export const PIPELINE_ACTION_NAMES = {
  ADD_EXEC_REPORT: "ADD_EXEC_REPORT",
  ADD_NOTE: "ADD_NOTE",
  ADD_SEQUENCE: "ADD_SEQUENCE",
  VIEW_PIPELINE_SEQUENCE: "VIEW_PIPELINE_SEQUENCE",
  SEND_EMAIL: "SEND_EMAIL",
  SEND_SMS: "SEND_SMS",
  UPDATE_STATUS: "UPDATE_STATUS",
  DLG_UPDATE_STATUS: "DLG_UPDATE_STATUS",
  UPDATE_SUBSTATUS: "UPDATE_SUBSTATUS",
  SUBMIT_CV: "SUBMIT_CV",
  VIEW_CANDIDATE_CV: "VIEW_CANDIDATE_CV",
  ADD_FOLDER: "ADD_FOLDER",
  UPDATE_OWNER: "UPDATE_OWNER",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
  UNREJECT: "UNREJECT",
  REASSIGN: "REASSIGN",
  EXPORT: "EXPORT",
  REMOVE: "REMOVE",
  SCHEDULE_INTERVIEW: "SCHEDULE_INTERVIEW",
  VIEW_PIPELINE_INTERVIEW: "VIEW_PIPELINE_INTERVIEW",
  ADD_EVENT: "ADD_EVENT",
  ADD_TASK: "ADD_TASK",
  PIPELINE_UPDATED: "PIPELINE_UPDATED",
  VIEW_RECORD: "VIEW_RECORD",
  UPDATE_COMMENTS: "UPDATE_COMMENTS",
  ADD_PLACEMENT: "ADD_PLACEMENT",
  VIEW_COMPANY: "VIEW_COMPANY",
  VIEW_JOB: "VIEW_JOB",
  VIEW_PLACEMENT: "VIEW_PLACEMENT",
};

export const JOB_PIPELINE_FILTERS = {
  searchValue: "searchValue",
  usersFilter: "usersFilter",
  userTypeFilter: "userTypeFilter",
  statusFilter: "statusFilter",
  stateFilter: "stateFilter",
  rejectReasonsFilter: "rejectReasonsFilter",
  dateFilter: "dateFilter",
};

export const STATE_FILTER_TYPES = {
  all: "ALL",
  active: "ACTIVE",
  rejected: "REJECTED",
};
